- hosts: db
  become_user: root
  remote_user: ubuntu
  become: true


  tasks:
    - name: Download Percona package
      get_url:
        url: https://repo.percona.com/apt/percona-release_0.1-4.xenial_all.deb
        dest: /home/ubuntu/

    - name: Run dpkg 
      command: dpkg -i percona-release_0.1-4.xenial_all.deb
      args:
        chdir: /home/ubuntu/
    
    - name: Run apt-get update
      apt:
         update_cache: yes

    - name: Install Percona package
      apt:
         name: percona-server-server-5.7
         update_cache: yes

    - name: Start db service
      service:
        name: mysql
        state: started

    - name: Install python-mysqldb
      apt:
         name: python-mysqldb
         update_cache: yes

    - name: Create user
      mysql_user:
        name: user
        host: 192.168.33.11
        password: password
        priv: '*.*:ALL,GRANT'
        state: present

    - mysql_user:
        name: user
        host: 192.168.33.12
        password: password
        priv: '*.*:ALL,GRANT'
        state: present

    - name: Create a new database with name 'test'
      mysql_db:
        name: test
        state: present

    - git:
        repo: 'https://github.com/hammerkid/PythonDevOpstask.git'
        dest: /home/ubuntu/db/
        version: db

    - name: Create database
      mysql_db:
        name: test
        state: import
        target: /home/ubuntu/db/sql_template.sql


- hosts: loadbalancer
  become_user: root
  remote_user: ubuntu
  become: true


  tasks:
    - name: Run apt-get update
      apt:
         update_cache: yes

    - name: Install the package "nginx"
      apt:
        name: nginx 
        state: present

    - name: Prepare nginx configs
      git:
        repo: 'https://github.com/hammerkid/PythonDevOpstask.git'
        dest: /home/ubuntu/configs/
        version: configs

    - name: Move config to conf.d
      command: mv /home/ubuntu/configs/dev-ops-app.conf /etc/nginx/conf.d/

    - name: Create soft link to sites enabled
      command: ln -s /etc/nginx/conf.d/dev-ops-app.conf  /etc/nginx/sites-enabled/
    
    - name: Move config to conf.d
      command: mv /home/ubuntu/configs/nginx.conf /etc/nginx/
    
    - name: Delete dafault soft link
      command: rm /etc/nginx/sites-enabled/default
      ignore_errors: yes

    - name: Restart nginx
      service:
        name: nginx
        state: restarted

###############################################

ql


- hosts: app2
  become_user: root
  remote_user: ubuntu
  become: true

  tasks:
    
    - name: Run apt-get update
      apt:
         update_cache: yes

    - name: Install list of packages
      apt: name={{item}} state=installed
      with_items:
           - build-essential
           - python-dev
           - python-mysqldb

    - name: Install uwsgi
      pip:
         name: uwsgi
         extra_args: -I --no-cache-dir

    - name: Copy app from git
      git:
         repo: 'https://github.com/hammerkid/PythonDevOpstask.git'
         dest: /home/ubuntu/app/
         version: app

    - name: Run uwsgi socket 
      command: uwsgi --socket :8000 --protocol=http -w wsgi
         chdir: /home/ubuntu/app

#    - name: Create dev-ops-app.service
#      command: cp /home/ubuntu/app/flaskapp/dev-ops-app.service /etc/systemd/system/
      
#    - name: Start dev-ops-app service
#      systemd: name=dev-ops-app state=starte

#    - name: Create dev-ops-app.service
#      command: systemctl daemon-reload





